//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI_Projekt
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class M120Entities1 : DbContext
    {
        public M120Entities1()
            : base("name=M120Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Hotel> Hotel { get; set; }
        public virtual DbSet<HotelBild> HotelBild { get; set; }
        public virtual DbSet<Kunde> Kunde { get; set; }
        public virtual DbSet<Kunde_Reise> Kunde_Reise { get; set; }
        public virtual DbSet<Land> Land { get; set; }
        public virtual DbSet<Reise> Reise { get; set; }
        public virtual DbSet<Reise_Hotel> Reise_Hotel { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
